manifest:
  remotes:
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: infused-kim
      revision: v2.5.0+zmk-fixes+kim-fixes
      import: app/west.yml
  self:
    path: config
